name: Vollständige Projektboard-Automatisierung

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, closed, labeled]

jobs:
  project-board-workflow:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
      project: write

    steps:
      - name: Add to Project Board
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/ATMedicalGmbH/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign Issue if labeled 'feature'
        if: github.event_name == 'issues' && github.event.label.name == 'feature'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: andreas-tremml
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Security Label Notification (simulate Slack)
        if: github.event_name == 'issues' && github.event.label.name == 'security'
        run: |
          echo "Sicherheits-Label erkannt – Nachricht an Sicherheitsteam senden"
          echo "ALARM: Sicherheits-Issue geöffnet: ${{ github.event.issue.html_url }}"

      - name: Log Action to File
        run: |
          mkdir -p workflow-logs
          echo "$(date) – Action ausgeführt für ${GITHUB_EVENT_NAME}" >> workflow-logs/action-log.txt

  pull-request-actions:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Mark PR for Review
        if: github.event.action == 'opened'
        run: echo "Pull Request geöffnet: ${{ github.event.pull_request.html_url }}"

      - name: Mark PR as Complete
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "Pull Request erfolgreich gemerged. Automatisch als 'Erledigt' markieren (manuell prüfen)."
