name: Deployment – Release to Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Node.js einrichten
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Abhängigkeiten installieren
      run: npm ci

    - name: Build durchführen
      run: npm run build

    - name: Auf Server deployen via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/prescriptcheck
          git pull origin main
          npm ci
          pm2 restart prescriptcheck || pm2 start index.js --name prescriptcheck
